// Code generated by mockery v2.53.6. DO NOT EDIT.

package interfaces

import (
	context "context"

	apimodel "github.com/arashackdev/doopl/v3/apimodel"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentHandler is an autogenerated mock type for the DocumentHandler type
type MockDocumentHandler struct {
	mock.Mock
}

type MockDocumentHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentHandler) EXPECT() *MockDocumentHandler_Expecter {
	return &MockDocumentHandler_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, docID, apiKey
func (_m *MockDocumentHandler) Download(ctx context.Context, docID string, apiKey string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, docID, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadCloser, error)); ok {
		return rf(ctx, docID, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) io.ReadCloser); ok {
		r0 = rf(ctx, docID, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, docID, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentHandler_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockDocumentHandler_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - apiKey string
func (_e *MockDocumentHandler_Expecter) Download(ctx interface{}, docID interface{}, apiKey interface{}) *MockDocumentHandler_Download_Call {
	return &MockDocumentHandler_Download_Call{Call: _e.mock.On("Download", ctx, docID, apiKey)}
}

func (_c *MockDocumentHandler_Download_Call) Run(run func(ctx context.Context, docID string, apiKey string)) *MockDocumentHandler_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDocumentHandler_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockDocumentHandler_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentHandler_Download_Call) RunAndReturn(run func(context.Context, string, string) (io.ReadCloser, error)) *MockDocumentHandler_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: ctx, docID, apiKey
func (_m *MockDocumentHandler) Status(ctx context.Context, docID string, apiKey string) (*apimodel.DocumentStatusResponse, error) {
	ret := _m.Called(ctx, docID, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *apimodel.DocumentStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*apimodel.DocumentStatusResponse, error)); ok {
		return rf(ctx, docID, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *apimodel.DocumentStatusResponse); ok {
		r0 = rf(ctx, docID, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.DocumentStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, docID, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentHandler_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockDocumentHandler_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - apiKey string
func (_e *MockDocumentHandler_Expecter) Status(ctx interface{}, docID interface{}, apiKey interface{}) *MockDocumentHandler_Status_Call {
	return &MockDocumentHandler_Status_Call{Call: _e.mock.On("Status", ctx, docID, apiKey)}
}

func (_c *MockDocumentHandler_Status_Call) Run(run func(ctx context.Context, docID string, apiKey string)) *MockDocumentHandler_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDocumentHandler_Status_Call) Return(_a0 *apimodel.DocumentStatusResponse, _a1 error) *MockDocumentHandler_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentHandler_Status_Call) RunAndReturn(run func(context.Context, string, string) (*apimodel.DocumentStatusResponse, error)) *MockDocumentHandler_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, file, filename, lang
func (_m *MockDocumentHandler) Upload(ctx context.Context, file io.Reader, filename string, lang string) (*apimodel.DocumentUploadResponse, error) {
	ret := _m.Called(ctx, file, filename, lang)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *apimodel.DocumentUploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) (*apimodel.DocumentUploadResponse, error)); ok {
		return rf(ctx, file, filename, lang)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) *apimodel.DocumentUploadResponse); ok {
		r0 = rf(ctx, file, filename, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.DocumentUploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = rf(ctx, file, filename, lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentHandler_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockDocumentHandler_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - filename string
//   - lang string
func (_e *MockDocumentHandler_Expecter) Upload(ctx interface{}, file interface{}, filename interface{}, lang interface{}) *MockDocumentHandler_Upload_Call {
	return &MockDocumentHandler_Upload_Call{Call: _e.mock.On("Upload", ctx, file, filename, lang)}
}

func (_c *MockDocumentHandler_Upload_Call) Run(run func(ctx context.Context, file io.Reader, filename string, lang string)) *MockDocumentHandler_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockDocumentHandler_Upload_Call) Return(_a0 *apimodel.DocumentUploadResponse, _a1 error) *MockDocumentHandler_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentHandler_Upload_Call) RunAndReturn(run func(context.Context, io.Reader, string, string) (*apimodel.DocumentUploadResponse, error)) *MockDocumentHandler_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentHandler creates a new instance of MockDocumentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentHandler {
	mock := &MockDocumentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
