// Code generated by mockery v2.53.6. DO NOT EDIT.

package interfaces

import (
	context "context"

	apimodel "github.com/arashackdev/doopl/internal/apimodel"

	mock "github.com/stretchr/testify/mock"
)

// MockLanguagesProvider is an autogenerated mock type for the LanguagesProvider type
type MockLanguagesProvider struct {
	mock.Mock
}

type MockLanguagesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLanguagesProvider) EXPECT() *MockLanguagesProvider_Expecter {
	return &MockLanguagesProvider_Expecter{mock: &_m.Mock}
}

// SourceLanguages provides a mock function with given fields: ctx
func (_m *MockLanguagesProvider) SourceLanguages(ctx context.Context) ([]apimodel.Language, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SourceLanguages")
	}

	var r0 []apimodel.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]apimodel.Language, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []apimodel.Language); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apimodel.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLanguagesProvider_SourceLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceLanguages'
type MockLanguagesProvider_SourceLanguages_Call struct {
	*mock.Call
}

// SourceLanguages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLanguagesProvider_Expecter) SourceLanguages(ctx interface{}) *MockLanguagesProvider_SourceLanguages_Call {
	return &MockLanguagesProvider_SourceLanguages_Call{Call: _e.mock.On("SourceLanguages", ctx)}
}

func (_c *MockLanguagesProvider_SourceLanguages_Call) Run(run func(ctx context.Context)) *MockLanguagesProvider_SourceLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLanguagesProvider_SourceLanguages_Call) Return(_a0 []apimodel.Language, _a1 error) *MockLanguagesProvider_SourceLanguages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLanguagesProvider_SourceLanguages_Call) RunAndReturn(run func(context.Context) ([]apimodel.Language, error)) *MockLanguagesProvider_SourceLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// TargetLanguages provides a mock function with given fields: ctx
func (_m *MockLanguagesProvider) TargetLanguages(ctx context.Context) ([]apimodel.Language, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TargetLanguages")
	}

	var r0 []apimodel.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]apimodel.Language, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []apimodel.Language); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apimodel.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLanguagesProvider_TargetLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetLanguages'
type MockLanguagesProvider_TargetLanguages_Call struct {
	*mock.Call
}

// TargetLanguages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLanguagesProvider_Expecter) TargetLanguages(ctx interface{}) *MockLanguagesProvider_TargetLanguages_Call {
	return &MockLanguagesProvider_TargetLanguages_Call{Call: _e.mock.On("TargetLanguages", ctx)}
}

func (_c *MockLanguagesProvider_TargetLanguages_Call) Run(run func(ctx context.Context)) *MockLanguagesProvider_TargetLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLanguagesProvider_TargetLanguages_Call) Return(_a0 []apimodel.Language, _a1 error) *MockLanguagesProvider_TargetLanguages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLanguagesProvider_TargetLanguages_Call) RunAndReturn(run func(context.Context) ([]apimodel.Language, error)) *MockLanguagesProvider_TargetLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function with given fields: ctx
func (_m *MockLanguagesProvider) Usage(ctx context.Context) (*apimodel.UsageResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *apimodel.UsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*apimodel.UsageResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *apimodel.UsageResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.UsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLanguagesProvider_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockLanguagesProvider_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLanguagesProvider_Expecter) Usage(ctx interface{}) *MockLanguagesProvider_Usage_Call {
	return &MockLanguagesProvider_Usage_Call{Call: _e.mock.On("Usage", ctx)}
}

func (_c *MockLanguagesProvider_Usage_Call) Run(run func(ctx context.Context)) *MockLanguagesProvider_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLanguagesProvider_Usage_Call) Return(_a0 *apimodel.UsageResponse, _a1 error) *MockLanguagesProvider_Usage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLanguagesProvider_Usage_Call) RunAndReturn(run func(context.Context) (*apimodel.UsageResponse, error)) *MockLanguagesProvider_Usage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLanguagesProvider creates a new instance of MockLanguagesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLanguagesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLanguagesProvider {
	mock := &MockLanguagesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
