// Code generated by mockery v2.53.6. DO NOT EDIT.

package interfaces

import (
	context "context"

	apimodel "github.com/arashackdev/doopl/internal/apimodel"

	mock "github.com/stretchr/testify/mock"
)

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function with given fields: ctx, req
func (_m *MockTranslator) Translate(ctx context.Context, req *apimodel.TranslateRequest) (*apimodel.TranslateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 *apimodel.TranslateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apimodel.TranslateRequest) (*apimodel.TranslateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apimodel.TranslateRequest) *apimodel.TranslateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.TranslateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apimodel.TranslateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTranslator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *apimodel.TranslateRequest
func (_e *MockTranslator_Expecter) Translate(ctx interface{}, req interface{}) *MockTranslator_Translate_Call {
	return &MockTranslator_Translate_Call{Call: _e.mock.On("Translate", ctx, req)}
}

func (_c *MockTranslator_Translate_Call) Run(run func(ctx context.Context, req *apimodel.TranslateRequest)) *MockTranslator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*apimodel.TranslateRequest))
	})
	return _c
}

func (_c *MockTranslator_Translate_Call) Return(_a0 *apimodel.TranslateResponse, _a1 error) *MockTranslator_Translate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTranslator_Translate_Call) RunAndReturn(run func(context.Context, *apimodel.TranslateRequest) (*apimodel.TranslateResponse, error)) *MockTranslator_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
