// Code generated by mockery v2.53.6. DO NOT EDIT.

package interfaces

import (
	context "context"

	apimodel "github.com/arashackdev/doopl/internal/apimodel"

	mock "github.com/stretchr/testify/mock"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Rephrase provides a mock function with given fields: ctx, req
func (_m *MockWriter) Rephrase(ctx context.Context, req *apimodel.RephraseRequest) (*apimodel.RephraseResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Rephrase")
	}

	var r0 *apimodel.RephraseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apimodel.RephraseRequest) (*apimodel.RephraseResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apimodel.RephraseRequest) *apimodel.RephraseResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.RephraseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apimodel.RephraseRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWriter_Rephrase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rephrase'
type MockWriter_Rephrase_Call struct {
	*mock.Call
}

// Rephrase is a helper method to define mock.On call
//   - ctx context.Context
//   - req *apimodel.RephraseRequest
func (_e *MockWriter_Expecter) Rephrase(ctx interface{}, req interface{}) *MockWriter_Rephrase_Call {
	return &MockWriter_Rephrase_Call{Call: _e.mock.On("Rephrase", ctx, req)}
}

func (_c *MockWriter_Rephrase_Call) Run(run func(ctx context.Context, req *apimodel.RephraseRequest)) *MockWriter_Rephrase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*apimodel.RephraseRequest))
	})
	return _c
}

func (_c *MockWriter_Rephrase_Call) Return(_a0 *apimodel.RephraseResponse, _a1 error) *MockWriter_Rephrase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWriter_Rephrase_Call) RunAndReturn(run func(context.Context, *apimodel.RephraseRequest) (*apimodel.RephraseResponse, error)) *MockWriter_Rephrase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
