// Code generated by mockery v2.53.6. DO NOT EDIT.

package interfaces

import (
	context "context"

	apimodel "github.com/arashackdev/doopl/internal/apimodel"

	mock "github.com/stretchr/testify/mock"
)

// MockGlossaryManager is an autogenerated mock type for the GlossaryManager type
type MockGlossaryManager struct {
	mock.Mock
}

type MockGlossaryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlossaryManager) EXPECT() *MockGlossaryManager_Expecter {
	return &MockGlossaryManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, sourceLang, targetLang, entries
func (_m *MockGlossaryManager) Create(ctx context.Context, name string, sourceLang string, targetLang string, entries map[string]string) (*apimodel.GlossaryResponse, error) {
	ret := _m.Called(ctx, name, sourceLang, targetLang, entries)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apimodel.GlossaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) (*apimodel.GlossaryResponse, error)); ok {
		return rf(ctx, name, sourceLang, targetLang, entries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) *apimodel.GlossaryResponse); ok {
		r0 = rf(ctx, name, sourceLang, targetLang, entries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.GlossaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]string) error); ok {
		r1 = rf(ctx, name, sourceLang, targetLang, entries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGlossaryManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGlossaryManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - sourceLang string
//   - targetLang string
//   - entries map[string]string
func (_e *MockGlossaryManager_Expecter) Create(ctx interface{}, name interface{}, sourceLang interface{}, targetLang interface{}, entries interface{}) *MockGlossaryManager_Create_Call {
	return &MockGlossaryManager_Create_Call{Call: _e.mock.On("Create", ctx, name, sourceLang, targetLang, entries)}
}

func (_c *MockGlossaryManager_Create_Call) Run(run func(ctx context.Context, name string, sourceLang string, targetLang string, entries map[string]string)) *MockGlossaryManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]string))
	})
	return _c
}

func (_c *MockGlossaryManager_Create_Call) Return(_a0 *apimodel.GlossaryResponse, _a1 error) *MockGlossaryManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGlossaryManager_Create_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]string) (*apimodel.GlossaryResponse, error)) *MockGlossaryManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, glossaryID
func (_m *MockGlossaryManager) Delete(ctx context.Context, glossaryID string) error {
	ret := _m.Called(ctx, glossaryID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, glossaryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGlossaryManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGlossaryManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - glossaryID string
func (_e *MockGlossaryManager_Expecter) Delete(ctx interface{}, glossaryID interface{}) *MockGlossaryManager_Delete_Call {
	return &MockGlossaryManager_Delete_Call{Call: _e.mock.On("Delete", ctx, glossaryID)}
}

func (_c *MockGlossaryManager_Delete_Call) Run(run func(ctx context.Context, glossaryID string)) *MockGlossaryManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGlossaryManager_Delete_Call) Return(_a0 error) *MockGlossaryManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGlossaryManager_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockGlossaryManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Entries provides a mock function with given fields: ctx, glossaryID
func (_m *MockGlossaryManager) Entries(ctx context.Context, glossaryID string) (*apimodel.GlossaryEntriesResponse, error) {
	ret := _m.Called(ctx, glossaryID)

	if len(ret) == 0 {
		panic("no return value specified for Entries")
	}

	var r0 *apimodel.GlossaryEntriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*apimodel.GlossaryEntriesResponse, error)); ok {
		return rf(ctx, glossaryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *apimodel.GlossaryEntriesResponse); ok {
		r0 = rf(ctx, glossaryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.GlossaryEntriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, glossaryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGlossaryManager_Entries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entries'
type MockGlossaryManager_Entries_Call struct {
	*mock.Call
}

// Entries is a helper method to define mock.On call
//   - ctx context.Context
//   - glossaryID string
func (_e *MockGlossaryManager_Expecter) Entries(ctx interface{}, glossaryID interface{}) *MockGlossaryManager_Entries_Call {
	return &MockGlossaryManager_Entries_Call{Call: _e.mock.On("Entries", ctx, glossaryID)}
}

func (_c *MockGlossaryManager_Entries_Call) Run(run func(ctx context.Context, glossaryID string)) *MockGlossaryManager_Entries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGlossaryManager_Entries_Call) Return(_a0 *apimodel.GlossaryEntriesResponse, _a1 error) *MockGlossaryManager_Entries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGlossaryManager_Entries_Call) RunAndReturn(run func(context.Context, string) (*apimodel.GlossaryEntriesResponse, error)) *MockGlossaryManager_Entries_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockGlossaryManager) List(ctx context.Context) (*apimodel.GlossariesResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apimodel.GlossariesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*apimodel.GlossariesResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *apimodel.GlossariesResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apimodel.GlossariesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGlossaryManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGlossaryManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGlossaryManager_Expecter) List(ctx interface{}) *MockGlossaryManager_List_Call {
	return &MockGlossaryManager_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockGlossaryManager_List_Call) Run(run func(ctx context.Context)) *MockGlossaryManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGlossaryManager_List_Call) Return(_a0 *apimodel.GlossariesResponse, _a1 error) *MockGlossaryManager_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGlossaryManager_List_Call) RunAndReturn(run func(context.Context) (*apimodel.GlossariesResponse, error)) *MockGlossaryManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGlossaryManager creates a new instance of MockGlossaryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGlossaryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGlossaryManager {
	mock := &MockGlossaryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
