// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	apimodel "github.com/arashackdev/doopl/internal/apimodel"
	model "github.com/arashackdev/doopl/pkg/model"
)

type APIToModelImpl struct{}

func (c *APIToModelImpl) DocumentStatus(source apimodel.DocumentStatusResponse) model.DocumentStatusInfo {
	var modelDocumentStatusInfo model.DocumentStatusInfo
	modelDocumentStatusInfo.DocumentID = source.DocumentID
	modelDocumentStatusInfo.Status = model.DocumentStatus(source.Status)
	if source.SecondsRemaining != nil {
		xint64 := *source.SecondsRemaining
		modelDocumentStatusInfo.SecondsRemaining = &xint64
	}
	if source.BilledCharacters != nil {
		xint642 := *source.BilledCharacters
		modelDocumentStatusInfo.BilledCharacters = &xint642
	}
	if source.CharacterCount != nil {
		xint643 := *source.CharacterCount
		modelDocumentStatusInfo.CharacterCount = &xint643
	}
	if source.ErrorMessage != nil {
		xstring := *source.ErrorMessage
		modelDocumentStatusInfo.ErrorMessage = &xstring
	}
	return modelDocumentStatusInfo
}
func (c *APIToModelImpl) Glossaries(source []apimodel.GlossaryResponse) []model.Glossary {
	var modelGlossaryList []model.Glossary
	if source != nil {
		modelGlossaryList = make([]model.Glossary, len(source))
		for i := 0; i < len(source); i++ {
			modelGlossaryList[i] = c.Glossary(source[i])
		}
	}
	return modelGlossaryList
}
func (c *APIToModelImpl) Glossary(source apimodel.GlossaryResponse) model.Glossary {
	var modelGlossary model.Glossary
	modelGlossary.GlossaryID = source.GlossaryID
	modelGlossary.Name = source.Name
	modelGlossary.Ready = source.Ready
	modelGlossary.SourceLang = source.SourceLang
	modelGlossary.TargetLang = source.TargetLang
	modelGlossary.CreationTime = source.CreationTime
	modelGlossary.EntryCount = source.EntryCount
	return modelGlossary
}
func (c *APIToModelImpl) Language(source apimodel.Language) model.Language {
	var modelLanguage model.Language
	modelLanguage.Code = source.Code
	modelLanguage.Name = source.Name
	if source.SupportsFormality != nil {
		xbool := *source.SupportsFormality
		modelLanguage.SupportsFormality = &xbool
	}
	return modelLanguage
}
func (c *APIToModelImpl) Languages(source []apimodel.Language) []model.Language {
	var modelLanguageList []model.Language
	if source != nil {
		modelLanguageList = make([]model.Language, len(source))
		for i := 0; i < len(source); i++ {
			modelLanguageList[i] = c.Language(source[i])
		}
	}
	return modelLanguageList
}
func (c *APIToModelImpl) Translation(source apimodel.Translation) model.TextResult {
	var modelTextResult model.TextResult
	modelTextResult.Text = source.Text
	modelTextResult.DetectedSourceLang = source.DetectedSourceLang
	modelTextResult.BilledCharacters = source.BilledCharacters
	modelTextResult.ModelTypeUsed = source.ModelTypeUsed
	return modelTextResult
}
func (c *APIToModelImpl) Translations(source []apimodel.Translation) []model.TextResult {
	var modelTextResultList []model.TextResult
	if source != nil {
		modelTextResultList = make([]model.TextResult, len(source))
		for i := 0; i < len(source); i++ {
			modelTextResultList[i] = c.Translation(source[i])
		}
	}
	return modelTextResultList
}
func (c *APIToModelImpl) Usage(source apimodel.UsageResponse) model.Usage {
	var modelUsage model.Usage
	modelUsage.CharacterCount = source.CharacterCount
	modelUsage.CharacterLimit = source.CharacterLimit
	modelUsage.DocumentCount = source.DocumentCount
	modelUsage.DocumentLimit = source.DocumentLimit
	modelUsage.TeamDocumentCount = source.TeamDocumentCount
	modelUsage.TeamDocumentLimit = source.TeamDocumentLimit
	return modelUsage
}
