package convert

// Converters used in this package:
//
// - APIToModel (defined in apimodel_to_model.go) converts wire format (apimodel)
//   to public domain types (model). Generated by goverter; implementation in converter_gen.go.
//   Depends on: apimodel, model
//
// Example interface methods:
//   Translation(source apimodel.Translation) model.TextResult
//   Translations(source []apimodel.Translation) []model.TextResult
//   Language(source apimodel.Language) model.Language
//   Languages(source []apimodel.Language) []model.Language
//   Usage(source apimodel.UsageResponse) model.Usage
//   DocumentStatus(source apimodel.DocumentStatusResponse) model.DocumentStatusInfo
//   Glossary(source apimodel.GlossaryResponse) model.Glossary
//   Glossaries(source []apimodel.GlossaryResponse) []model.Glossary
//
// See: apimodel_to_model.go (interface definition + goverter directives)
//      converter_gen.go (generated implementation)
//      ../../../pkg/model/ (public domain types)
