// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	entity "github.com/arashackdev/doopl/cmd/doopl/internal/entity"
	model "github.com/arashackdev/doopl/pkg/model"
)

type ModelToEntityImpl struct{}

func (c *ModelToEntityImpl) LanguageRow(source model.Language) entity.LanguageRow {
	var entityLanguageRow entity.LanguageRow
	entityLanguageRow.Code = source.Code
	entityLanguageRow.Name = source.Name
	if source.SupportsFormality != nil {
		xbool := *source.SupportsFormality
		entityLanguageRow.SupportsFormality = &xbool
	}
	return entityLanguageRow
}
func (c *ModelToEntityImpl) LanguageRows(source []model.Language) []entity.LanguageRow {
	var entityLanguageRowList []entity.LanguageRow
	if source != nil {
		entityLanguageRowList = make([]entity.LanguageRow, len(source))
		for i := 0; i < len(source); i++ {
			entityLanguageRowList[i] = c.LanguageRow(source[i])
		}
	}
	return entityLanguageRowList
}
func (c *ModelToEntityImpl) TranslationRow(source model.TextResult) entity.TranslationRow {
	var entityTranslationRow entity.TranslationRow
	entityTranslationRow.Text = source.Text
	entityTranslationRow.DetectedSourceLang = source.DetectedSourceLang
	entityTranslationRow.BilledCharacters = source.BilledCharacters
	return entityTranslationRow
}
func (c *ModelToEntityImpl) TranslationRows(source []model.TextResult) []entity.TranslationRow {
	var entityTranslationRowList []entity.TranslationRow
	if source != nil {
		entityTranslationRowList = make([]entity.TranslationRow, len(source))
		for i := 0; i < len(source); i++ {
			entityTranslationRowList[i] = c.TranslationRow(source[i])
		}
	}
	return entityTranslationRowList
}
func (c *ModelToEntityImpl) UsageRow(source model.Usage) entity.UsageRow {
	var entityUsageRow entity.UsageRow
	entityUsageRow.CharacterCount = source.CharacterCount
	entityUsageRow.CharacterLimit = source.CharacterLimit
	entityUsageRow.DocumentCount = source.DocumentCount
	entityUsageRow.DocumentLimit = source.DocumentLimit
	entityUsageRow.TeamDocumentCount = source.TeamDocumentCount
	entityUsageRow.TeamDocumentLimit = source.TeamDocumentLimit
	return entityUsageRow
}
