package convert

// Converters used in this package:
//
// - ModelToEntity (defined in model_to_entity.go) converts public domain types (model)
//   to CLI display entities (entity) for formatted output (JSON, table, text).
//   Generated by goverter; implementation in converter_gen.go.
//   Depends on: entity, model
//
// Example interface methods:
//   TranslationRow(source model.TextResult) entity.TranslationRow
//   TranslationRows(source []model.TextResult) []entity.TranslationRow
//   LanguageRow(source model.Language) entity.LanguageRow
//   LanguageRows(source []model.Language) []entity.LanguageRow
//   UsageRow(source model.Usage) entity.UsageRow
//
// See: model_to_entity.go (interface definition + goverter directives)
//      converter_gen.go (generated implementation)
//      ../entity/ (CLI display types)
