package deepl

// Dependencies used by this package:
//
// - internal/transport.Transport: Low-level HTTP with auth, retry, backoff, User-Agent.
//   Handles: Do(ctx, req Request) (*http.Response, error)
//   Used by: translate.go, document.go, glossary.go, languages.go, write.go
//   See: ../../internal/transport/transport.go
//
// - internal/convert.APIToModel (generated by goverter): Converts between
//   API wire format (apimodel) and public domain types (model).
//   Used by: translate.go, document.go, glossary.go, languages.go, write.go
//   See: ../../internal/convert/apimodel_to_model.go (interface)
//        ../../internal/convert/converter_gen.go (generated implementation)
//
// - internal/apimodel: API wire format types matching DeepL v3 JSON schema.
//   Used by: All API methods to unmarshal responses.
//   See: ../../internal/apimodel/
//
// - pkg/model: Public domain types exported to users (TextResult, Glossary, etc.).
//   Used by: All API methods in their return types.
//   See: ../../pkg/model/
